spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crafts
    username: postgres
    password: Tikaflakour@94
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg%n"
  level:
    com:
      nwn:
        crafts: DEBUG
